# Generated by Django 2.2 on 2020-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=10000, verbose_name='Description'),
        ),
    ]
